title: Adam Kaewell
email: adam.kaewell@gmail.com
email_short: adam.kaewell
description: Software engineer, outdoor enthusiast, seeker of knowledge, gamer.
baseurl: 
url: https://adam.kaewell.com

twitter:
  username: akaewell
  url: https://twitter.com/akaewell
github:
  username: a2k11
  url: https://github.com/a2k11

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

defaults:
  - 
    scope:
      path: ""
    values: 
      layout: "post"
